"""Initial models with indexes

Revision ID: e7d31d65bd58
Revises: 
Create Date: 2026-09-09 15:53:53.876276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d31d65bd58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('api_specs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_specs_created_at'), 'api_specs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_specs_id'), 'api_specs', ['id'], unique=False)
    op.create_index(op.f('ix_api_specs_project_id'), 'api_specs', ['project_id'], unique=False)
    op.create_table('playground_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playground_requests_created_at'), 'playground_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_playground_requests_id'), 'playground_requests', ['id'], unique=False)
    op.create_index(op.f('ix_playground_requests_project_id'), 'playground_requests', ['project_id'], unique=False)
    op.create_table('generated_sdks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_spec_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('sdk_code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['api_spec_id'], ['api_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_sdks_api_spec_id'), 'generated_sdks', ['api_spec_id'], unique=False)
    op.create_index(op.f('ix_generated_sdks_created_at'), 'generated_sdks', ['created_at'], unique=False)
    op.create_index(op.f('ix_generated_sdks_id'), 'generated_sdks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_sdks_id'), table_name='generated_sdks')
    op.drop_index(op.f('ix_generated_sdks_created_at'), table_name='generated_sdks')
    op.drop_index(op.f('ix_generated_sdks_api_spec_id'), table_name='generated_sdks')
    op.drop_table('generated_sdks')
    op.drop_index(op.f('ix_playground_requests_project_id'), table_name='playground_requests')
    op.drop_index(op.f('ix_playground_requests_id'), table_name='playground_requests')
    op.drop_index(op.f('ix_playground_requests_created_at'), table_name='playground_requests')
    op.drop_table('playground_requests')
    op.drop_index(op.f('ix_api_specs_project_id'), table_name='api_specs')
    op.drop_index(op.f('ix_api_specs_id'), table_name='api_specs')
    op.drop_index(op.f('ix_api_specs_created_at'), table_name='api_specs')
    op.drop_table('api_specs')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
