import datetime
import re
import jinja2
from typing import Dict, Any, List
from ..parsers.openapi import NormalizedAPISpec

PYTHON_SDK_TEMPLATE = """# Generated by Doc2SDK
# API: {{ name }} v{{ version }}
# Generated: {{ generated_at }}

from typing import Optional, Dict, Any, List
import httpx
import logging

logger = logging.getLogger(__name__)

class {{ name | sanitize_class }}APIError(Exception):
    \"\"\"Base exception for {{ name }} API errors\"\"\"
    def __init__(self, message: str, status_code: int, response: Dict):
        self.message = message
        self.status_code = status_code
        self.response = response
        super().__init__(self.message)

class {{ name | sanitize_class }}Client:
    \"\"\"
    {{ name }} API Client
    \"\"\"
    
    def __init__(
        self,
        api_key: str = None,
        base_url: str = "{{ base_url or 'https://api.example.com' }}",
        timeout: int = 30,
        max_retries: int = 3
    ):
        self.api_key = api_key
        self.base_url = base_url
        self.timeout = timeout
        self.max_retries = max_retries
        
        headers = {
            "Content-Type": "application/json",
            "User-Agent": "Doc2SDK-SDK/1.0"
        }
        if api_key:
            {% if authentication.type == 'bearer' %}
            headers["Authorization"] = f"Bearer {api_key}"
            {% elif authentication.type == 'apiKey' %}
            headers["{{ authentication.name or 'X-API-Key' }}"] = api_key
            {% endif %}

        self.client = httpx.Client(
            base_url=base_url,
            timeout=timeout,
            headers=headers
        )

    {% for endpoint in endpoints %}
    def {{ (endpoint.summary or (endpoint.method + endpoint.path)) | sanitize }}(
        self,
        {% if endpoint.parameters and endpoint.parameters.path %}
        {% for p in endpoint.parameters.path %}
        {{ p.name | sanitize }}: str = "default",
        {% endfor %}
        {% endif %}
        **kwargs
    ) -> Dict[str, Any]:
        \"\"\"
        {{ endpoint.summary or endpoint.path }}
        {{ endpoint.description }}
        \"\"\"
        path = f"{{ endpoint.path }}"
        {% if endpoint.parameters and endpoint.parameters.path %}
        {% for p in endpoint.parameters.path %}
        path = path.replace("{{ '{' + p.name + '}' }}", str({{ p.name | sanitize }}))
        {% endfor %}
        {% endif %}
        
        try:
            response = self.client.request(
                "{{ endpoint.method }}",
                path,
                params=kwargs.get("params"),
                json=kwargs.get("json"),
                headers=kwargs.get("headers")
            )
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            raise {{ name | sanitize_class }}APIError(
                message=str(e),
                status_code=e.response.status_code,
                response=e.response.json() if e.response.content else {}
            )
    {% endfor %}

    def close(self):
        self.client.close()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
"""

TYPESCRIPT_SDK_TEMPLATE = """/**
 * Generated by Doc2SDK
 * API: {{ name }} v{{ version }}
 * Generated: {{ generated_at }}
 */

import axios, { AxiosInstance, AxiosError } from 'axios';

export class {{ name | sanitize_class }}APIError extends Error {
    constructor(
        public message: string,
        public statusCode?: number,
        public response?: any
    ) {
        super(message);
        this.name = '{{ name | sanitize_class }}APIError';
    }
}

export interface {{ name | sanitize_class }}Config {
    apiKey?: string;
    baseUrl?: string;
    timeout?: number;
}

export class {{ name | sanitize_class }}Client {
    private client: AxiosInstance;

    constructor(config: {{ name | sanitize_class }}Config = {}) {
        const {
            apiKey,
            baseUrl = "{{ base_url or 'https://api.example.com' }}",
            timeout = 30000
        } = config;

        const headers: Record<string, string> = {
            'Content-Type': 'application/json',
            'User-Agent': 'Doc2SDK-SDK/1.0'
        };

        if (apiKey) {
            {% if authentication.type == 'bearer' %}
            headers['Authorization'] = `Bearer ${apiKey}`;
            {% elif authentication.type == 'apiKey' %}
            headers['{{ authentication.name or "X-API-Key" }}'] = apiKey;
            {% endif %}
        }

        this.client = axios.create({
            baseURL: baseUrl,
            timeout,
            headers
        });
    }

    {% for endpoint in endpoints %}
    /**
     * {{ endpoint.summary or endpoint.path }}
     * {{ endpoint.description }}
     */
    async {{ (endpoint.summary or (endpoint.method + endpoint.path)) | sanitize_ts }}(
        {% if endpoint.parameters and endpoint.parameters.path %}
        {% for p in endpoint.parameters.path %}
        {{ p.name | sanitize }}: any = "default",
        {% endfor %}
        {% endif %}
        data?: any,
        params?: any
    ): Promise<any> {
        let path = `{{ endpoint.path }}`;
        {% if endpoint.parameters and endpoint.parameters.path %}
        {% for p in endpoint.parameters.path %}
        path = path.replace("{{ '{' + p.name + '}' }}", String({{ p.name | sanitize }}));
        {% endfor %}
        {% endif %}

        try {
            const response = await this.client.request({
                method: '{{ endpoint.method }}',
                url: path,
                data,
                params
            });
            return response.data;
        } catch (error) {
            const axiosError = error as AxiosError;
            throw new {{ name | sanitize_class }}APIError(
                axiosError.message,
                axiosError.response?.status,
                axiosError.response?.data
            );
        }
    }
    {% endfor %}
}
"""

PYTHON_TESTS_TEMPLATE = """# Auto-generated Test Suite by Doc2SDK
# API: {{ name }} v{{ version }}
# Generated: {{ generated_at }}
#
# Run with: pytest test_sdk.py -v

import pytest
import httpx
from unittest.mock import MagicMock, patch

# In production, import your generated client:
# from sdk import {{ name | sanitize_class }}Client, {{ name | sanitize_class }}APIError


@pytest.fixture
def mock_client():
    \"\"\"Fixture providing a mock client session with mocked httpx transport.\"\"\"
    with patch("httpx.Client.request") as mock_request:
        # We define a dummy client interface if not imported
        class DummyClient:
            def __init__(self, api_key=None, base_url="{{ base_url or 'https://api.example.com' }}"):
                self.api_key = api_key
                self.base_url = base_url

            def _call(self, method, path, params=None, json=None, headers=None):
                res = mock_request(method, path, params=params, json=json, headers=headers)
                res.raise_for_status()
                return res.json()

            {% for endpoint in endpoints %}
            def {{ (endpoint.summary or (endpoint.method + endpoint.path)) | sanitize }}(self, {% if endpoint.parameters and endpoint.parameters.path %}{% for p in endpoint.parameters.path %}{{ p.name | sanitize }}="val", {% endfor %}{% endif %}**kwargs):
                path = "{{ endpoint.path }}"
                {% if endpoint.parameters and endpoint.parameters.path %}
                {% for p in endpoint.parameters.path %}
                path = path.replace("{{ '{' + p.name + '}' }}", str({{ p.name | sanitize }}))
                {% endfor %}
                {% endif %}
                return self._call("{{ endpoint.method }}", path, params=kwargs.get("params"), json=kwargs.get("json"))
            {% endfor %}

        client = DummyClient(api_key="test_key_123")
        yield client, mock_request


class Test{{ name | sanitize_class }}Endpoints:
    \"\"\"Comprehensive unit and integration test suite for {{ name }} endpoints.\"\"\"

    {% for endpoint in endpoints %}
    {% set method_name = (endpoint.summary or (endpoint.method + endpoint.path)) | sanitize %}
    def test_{{ method_name }}_success(self, mock_client):
        \"\"\"Test successful execution (200 OK) for {{ endpoint.method }} {{ endpoint.path }}\"\"\"
        client, mock_request = mock_client
        mock_response = MagicMock(spec=httpx.Response)
        mock_response.status_code = 200
        mock_response.json.return_value = {"status": "success", "data": {"id": 1, "test": True}}
        mock_response.raise_for_status.return_value = None
        mock_request.return_value = mock_response

        # Execute endpoint call
        result = client.{{ method_name }}(
            {% if endpoint.parameters and endpoint.parameters.path %}
            {% for p in endpoint.parameters.path %}
            {{ p.name | sanitize }}="sample_{{ p.name }}",
            {% endfor %}
            {% endif %}
            {% if endpoint.parameters and endpoint.parameters.query %}
            params={
                {% for q in endpoint.parameters.query %}
                "{{ q.name }}": "{{ q.example or 'test' }}",
                {% endfor %}
            },
            {% endif %}
            {% if endpoint.request_body %}
            json={"mock_key": "mock_value"},
            {% endif %}
        )

        assert result is not None
        assert result.get("status") == "success"
        mock_request.assert_called_once()
        assert mock_request.call_args[0][0] == "{{ endpoint.method }}"

    def test_{{ method_name }}_client_error(self, mock_client):
        \"\"\"Test 400 Bad Request error handling for {{ endpoint.method }} {{ endpoint.path }}\"\"\"
        client, mock_request = mock_client
        err_res = MagicMock(spec=httpx.Response)
        err_res.status_code = 400
        err_res.json.return_value = {"error": "Invalid request parameter"}
        err_res.raise_for_status.side_effect = httpx.HTTPStatusError("400 Bad Request", request=MagicMock(), response=err_res)
        mock_request.return_value = err_res

        with pytest.raises(httpx.HTTPStatusError) as exc_info:
            client.{{ method_name }}(
                {% if endpoint.parameters and endpoint.parameters.path %}
                {% for p in endpoint.parameters.path %}
                {{ p.name | sanitize }}="bad_val",
                {% endfor %}
                {% endif %}
            )
        assert exc_info.value.response.status_code == 400

    def test_{{ method_name }}_server_error(self, mock_client):
        \"\"\"Test 500 Internal Server Error handling for {{ endpoint.method }} {{ endpoint.path }}\"\"\"
        client, mock_request = mock_client
        err_res = MagicMock(spec=httpx.Response)
        err_res.status_code = 500
        err_res.json.return_value = {"error": "Internal Server Error"}
        err_res.raise_for_status.side_effect = httpx.HTTPStatusError("500 Server Error", request=MagicMock(), response=err_res)
        mock_request.return_value = err_res

        with pytest.raises(httpx.HTTPStatusError) as exc_info:
            client.{{ method_name }}(
                {% if endpoint.parameters and endpoint.parameters.path %}
                {% for p in endpoint.parameters.path %}
                {{ p.name | sanitize }}="val",
                {% endfor %}
                {% endif %}
            )
        assert exc_info.value.response.status_code == 500
    {% endfor %}
"""

TYPESCRIPT_TESTS_TEMPLATE = """/**
 * Auto-generated Test Suite by Doc2SDK
 * API: {{ name }} v{{ version }}
 * Generated: {{ generated_at }}
 *
 * Run with: npm test or npx jest
 */

import { {{ name | sanitize_class }}Client, {{ name | sanitize_class }}APIError } from './client';
import axios from 'axios';

jest.mock('axios');
const mockedAxios = axios as jest.Mocked<typeof axios>;

describe('{{ name | sanitize_class }}Client Test Suite', () => {
    let client: {{ name | sanitize_class }}Client;
    const mockAxiosInstance = {
        request: jest.fn()
    };

    beforeEach(() => {
        jest.clearAllMocks();
        (axios.create as jest.Mock).mockReturnValue(mockAxiosInstance);
        client = new {{ name | sanitize_class }}Client({
            apiKey: 'test_token_123',
            baseUrl: '{{ base_url or "https://api.example.com" }}'
        });
    });

    {% for endpoint in endpoints %}
    {% set method_name = (endpoint.summary or (endpoint.method + endpoint.path)) | sanitize_ts %}
    describe('{{ method_name }}', () => {
        it('should successfully execute {{ endpoint.method }} {{ endpoint.path }}', async () => {
            const mockData = { status: 'success', data: { id: 1 } };
            mockAxiosInstance.request.mockResolvedValueOnce({ data: mockData, status: 200 });

            const result = await client.{{ method_name }}(
                {% if endpoint.parameters and endpoint.parameters.path %}
                {% for p in endpoint.parameters.path %}
                'sample_{{ p.name }}',
                {% endfor %}
                {% endif %}
                { example: 'body' }
            );

            expect(result).toEqual(mockData);
            expect(mockAxiosInstance.request).toHaveBeenCalled();
        });

        it('should handle API errors for {{ endpoint.method }} {{ endpoint.path }}', async () => {
            const error = {
                message: 'Request failed with status code 404',
                response: { status: 404, data: { detail: 'Not Found' } }
            };
            mockAxiosInstance.request.mockRejectedValueOnce(error);

            await expect(
                client.{{ method_name }}(
                    {% if endpoint.parameters and endpoint.parameters.path %}
                    {% for p in endpoint.parameters.path %}
                    'invalid_id',
                    {% endfor %}
                    {% endif %}
                )
            ).rejects.toThrow({{ name | sanitize_class }}APIError);
        });
    });
    {% endfor %}
});
"""


def sanitize_identifier(text: str) -> str:
    """Converts a string into a valid identifier (snake_case)."""
    if not text:
        return "endpoint"
    cleaned = re.sub(r'[^a-zA-Z0-9]', '_', text)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    cleaned = re.sub(r'_+', '_', cleaned)
    cleaned = cleaned.strip('_')
    return cleaned.lower() or "endpoint"


def sanitize_camel_case(text: str) -> str:
    """Converts a string into a valid camelCase identifier."""
    snake = sanitize_identifier(text)
    parts = snake.split('_')
    if len(parts) == 1:
        return parts[0]
    return parts[0] + ''.join(p.capitalize() for p in parts[1:])


def sanitize_class_name(text: str) -> str:
    """Converts a string into a valid PascalCase class name."""
    if not text:
        return "Api"
    cleaned = re.sub(r'[^a-zA-Z0-9]', ' ', text)
    words = cleaned.split()
    if not words:
        return "Api"
    return "".join(w[0].upper() + w[1:] for w in words)


class CodeGenerator:
    def __init__(self):
        self.env = jinja2.Environment()
        self.env.filters['sanitize'] = sanitize_identifier
        self.env.filters['sanitize_ts'] = sanitize_camel_case
        self.env.filters['sanitize_class'] = sanitize_class_name
        
        # Pre-compile templates to save time during generation
        self.python_sdk_template = self.env.from_string(PYTHON_SDK_TEMPLATE)
        self.ts_sdk_template = self.env.from_string(TYPESCRIPT_SDK_TEMPLATE)
        self.python_tests_template = self.env.from_string(PYTHON_TESTS_TEMPLATE)
        self.ts_tests_template = self.env.from_string(TYPESCRIPT_TESTS_TEMPLATE)

    def generate_sdk(self, spec: NormalizedAPISpec, language: str = "python") -> str:
        if language.lower() == "python":
            template = self.python_sdk_template
        elif language.lower() in ["typescript", "ts"]:
            template = self.ts_sdk_template
        else:
            raise ValueError(f"Language {language} not supported")

        return template.render(
            name=spec.name,
            version=spec.version,
            base_url=spec.base_url,
            authentication=spec.authentication,
            endpoints=spec.endpoints,
            generated_at=datetime.datetime.now(datetime.timezone.utc).isoformat()
        )

    def generate_python_sdk(self, spec: NormalizedAPISpec) -> str:
        return self.generate_sdk(spec, "python")

    def generate_tests(self, spec: NormalizedAPISpec, language: str = "python") -> str:
        """
        Generates executable unit & integration tests for all endpoints in the spec.
        """
        if language.lower() == "python":
            template = self.python_tests_template
        elif language.lower() in ["typescript", "ts"]:
            template = self.ts_tests_template
        else:
            raise ValueError(f"Language {language} not supported for test generation")

        return template.render(
            name=spec.name,
            version=spec.version,
            base_url=spec.base_url,
            authentication=spec.authentication,
            endpoints=spec.endpoints,
            generated_at=datetime.datetime.now(datetime.timezone.utc).isoformat()
        )

    def generate_python_tests(self, spec: NormalizedAPISpec) -> str:
        return self.generate_tests(spec, "python")
